services:
    steevobb.owncloudallowed.listener:
        class: steevobb\owncloudallowed\event\listener
        arguments:
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }
